#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

// 1. 基础音频与按键
#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000
#define AUDIO_I2S_METHOD_SIMPLEX
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_4
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_5
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_6
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_15
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_16
#define BUILTIN_LED_GPIO        GPIO_NUM_48
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define TOUCH_BUTTON_GPIO       GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC
#define LAMP_GPIO               GPIO_NUM_18

// 2. ST7789 强制驱动定义
#define LCD_TYPE_ST7789_SERIAL   1
#define DISPLAY_CLK_PIN        GPIO_NUM_21
#define DISPLAY_MOSI_PIN       GPIO_NUM_47
#define DISPLAY_RST_PIN        GPIO_NUM_45
#define DISPLAY_DC_PIN         GPIO_NUM_40
#define DISPLAY_CS_PIN         GPIO_NUM_41
#define DISPLAY_BACKLIGHT_PIN  GPIO_NUM_42

// 兼容旧代码搜索
#define DISPLAY_SDA_PIN        GPIO_NUM_47
#define DISPLAY_SCL_PIN        GPIO_NUM_21

// 3. 长方形屏幕规格
#define DISPLAY_WIDTH          240
#define DISPLAY_HEIGHT         280  // 如果画面底部不全，改为 320
#define DISPLAY_OFFSET_X       0
#define DISPLAY_OFFSET_Y       20   // 长方形屏幕常见的 Y 轴偏移
#define DISPLAY_INVERT_COLOR   true
#define DISPLAY_MIRROR_X       false
#define DISPLAY_MIRROR_Y       false
#define DISPLAY_SWAP_XY        false

#ifndef LCD_RGB_ELEMENT_ORDER_RGB
#define LCD_RGB_ELEMENT_ORDER_RGB 0
#endif
#define DISPLAY_RGB_ORDER       LCD_RGB_ELEMENT_ORDER_RGB
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false
#define DISPLAY_SPI_MODE        0

#endif // _BOARD_CONFIG_H_
